version: "3.4"

services:
  dbMariadb:
    image: mariadb:10.5.2
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME_PRODUCTION}
    volumes:
      - mariadb-data:/var/lib/mysql

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 8080:8080

  sonarqube:
    image: sonarqube:8-community
    restart: on-failure
    ports:
      - 12000:9000

volumes:
  mariadb-data:
