"""empty message

Revision ID: c8c522b5d9c9
Revises: 
Create Date: 2020-04-05 17:09:47.967537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8c522b5d9c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=False))
    op.drop_index('mobile_number', table_name='users')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('mobile_number', 'users', ['mobile_number'], unique=True)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
